export const GET_ALL_BlOGS_REQUEST = "ALL_BLOGS/GET_ALL_BLOGS_REQUEST";
export const GET_ALL_BLOGS_SUCCESS = "ALL_BLOGS/GET_ALL_BLOGS_SUCCESS";
export const GET_ALL_BLOGS_FAILURE = "ALL_BLOGS/GET_ALL_BLOGS_FAILURE";

export const GET_SINGLE_BlOG_REQUEST = "SINGLE_BLOG/GET_SINGLE_BLOG_REQUEST";
export const GET_SINGLE_BLOG_SUCCESS = "SINGLE_BLOG/GET_SINGLE_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_FAILURE = "SINGLE_BLOG/GET_SINGLE_BLOG_FAILURE";

